FROM rust:alpine as rust-build
WORKDIR /home/app

# Chỉ copy 2 files này để cài dependencies trước:
COPY Cargo.toml ./
RUN mkdir src && echo 'fn main() {}' > src/main.rs


# Chỉ cài download dependencies:
RUN cargo fetch

# Mẹo: tạo file main.rs trống rồi chạy cargo build để chỉ compile dependencies:
# Do app chúng mình ở trong folder src nên phải tạo một thư mục src trống trước để có thể tạo file main.rs:
RUN mkdir -p src && echo 'fn main() {}' > src/main.rs
RUN cargo build --release

# Giờ mình xóa cái thư mục src mình vừa tạo ở trên:
RUN rm -rf src

# Giờ copy source code thực sự và build app,
# Lúc này thì do dependencies đã được compile ở bước trên, nên rust chỉ cần compile mỗi app của bạn.
# Điều này sẽ giúp giảm thời gian build docker image khi các layer bên trên đều được cache.
COPY . .
RUN cargo build --release
RUN rm ./target/release/deps/socket*
RUN cargo install --path .

FROM alpine
WORKDIR /home/app


COPY --from=rust-build /home/app/target/release/socket .
CMD ["./socket"]