# version: "3.6"

services:
  shartube-mongo-db:
    container_name: shartube-mongo-db
    image: mongo
    networks:
      - shartube-net
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    restart: always
    volumes:
      - mongoDB:/data/db
    command: --quiet --logpath /dev/null

  redis:
    image: redis:alpine
    container_name: shartube-redis
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    networks:
      - shartube-net
    volumes: 
      - redis:/data

  shartube-graphql-gateway:
    container_name: shartube-graphql-gateway
    image: tritranduc11/shartube-graphql-gateway
    networks:
      - shartube-net
    depends_on:
      - shartube-comic-server
      - shartube-user-server
    build: ./graphql-gateway
    env_file:
      - ./graphql-gateway/.env
      - ./.base.env
    restart: always
    volumes:
      - ./graphql-gateway/router.yaml:/app/dev/router.yaml
      - ./graphql-gateway/supergraph.yaml:/app/dev/supergraph.yaml

  shartube-comic-server:
    container_name: shartube-comic-server
    image: tritranduc11/shartube-comic-server
    networks:
      - shartube-net
    depends_on:
      - shartube-mongo-db
      - shartube-user-server
      - redis
    build: ./comic
    env_file:
      - ./comic/.env
      - ./.base.env
    restart: always
    expose:
      - 8080


  shartube-user-server:
    container_name: shartube-user-server
    image: tritranduc11/shartube-user-server
    networks:
      - shartube-net
    depends_on:
      - shartube-mongo-db
    build: ./user
    env_file:
      - ./user/.env
      - ./.base.env
    restart: always
    expose:
      - 8080
    volumes:
      - ./user/src/secret:/app/dist/secret

  shartube-upload-server:
    container_name: shartube-upload-server
    image: tritranduc11/shartube-upload-server
    networks:
      - shartube-net
    build: ./cdn-service
    env_file:
      - ./cdn-service/.env
      - ./.base.env
    restart: always
    expose:
      - 3000
    environment:
      - CHANNEL_ID=1043368131390885968
  
  shartube-api-gateway:
    container_name: shartube-api-gateway
    image: tritranduc11/shartube-api-gateway
    networks:
      - shartube-net
    depends_on:
      - shartube-graphql-gateway
    build: ./api-gateway
    env_file:
      - ./.base.env
    restart: always
    expose:
      - 8080
    environment:
      - PORT=8080
    ports:
      - "8080:8080"
  
  shartube-meme-server:
    container_name: shartube-meme-server
    image: tritranduc11/shartube-meme-server
    networks:
      - shartube-net
    depends_on:
      - shartube-mongo-db
      
    build: ./meme
    env_file:
      - ./.base.env
    restart: always
    expose:
      - 8080
    environment:
      - PORT=8080
  shartube-like-server:
    container_name: shartube-like-server
    image: tritranduc11/shartube-like-server
    networks:
      - shartube-net
    depends_on:
      - shartube-mongo-db
      
    build: ./like-service
    env_file:
      - ./.base.env
    restart: always
    expose:
      - 8080
    environment:
      - PORT=8080  	
   

networks:
  shartube-net:

volumes:
  mongoDB:
  redis:
